#!/bin/bash

originalLDFlagsCache=originalLDFLAGS.txt

clean() {
    local target=${1}
    local what=${2}

    local bc=${target}.0.6.coverage.bc
    local o=${target}.coverage.o
    local exe=${target}.coverage
    rm -f ${bc} ${o} ${exe} *.blocks.map

    if [[ "${what}" == "coverage" ]]; then
        return
    fi

    rm -f ${target}.*
    make clean

    if [[ "${what}" == "all" ]]; then
        rm -f ${originalLDFlagsCache}
    fi
}

fuzz() {
	local buildDir=${__buildDir}
	local srcDir=${__srcDir}

    if [[ $# == 0 ]]; then
        echo "usage: ${0} <target executable> [-clean [coverage | all]]"
        return 1
    fi
    local target=${1}
    local option=${2}
    if [[ "${option}" == "-clean" ]]; then
        clean ${target} ${3}
        return
    fi

    # exit when any command fails
    set -e

    # keep track of the last executed command
    local currentCommand=
    local lastCommand=
    trap 'echo "\"${lastCommand}\" command filed with exit code $?."' EXIT
    trap 'local lastCommand=${currentCommand}; local currentCommand=${BASH_COMMAND}' DEBUG
    # echo an error message before exiting

    local flto="-flto -fuse-ld=lld" # flto makes .o files .bc files
    local myLDFLAGS="${flto} -Wl,-plugin-opt=save-temps" # generates .bc files also

	local cc=clang
	local cxx=clang++
	local ranlib=llvm-ranlib
	local cFlags=" -flto ${CFLAGS} "
	local ldFlags=" ${myLDFLAGS} ${LDFLAGS} "

	local originalLDFLAGS=""
    if [[ "${option}" == "-coverage" ]]; then
        if [[ -f "${originalLDFlagsCache}" ]]; then
        	originalLDFLAGS=$(cat "${originalLDFlagsCache}")
    	fi
    else
    	if [[ -f "${originalLDFlagsCache}" ]]; then
        	true
    	else
        	# only run configure once
        	CC=${cc} CXX=${cxx} RANLIB=${ranlib} CFLAGS=${cFlags} LDFLAGS=${ldFlags} ./configure
        	rm -f a.out.* # generated by autotools for testing
        	# need these for final link
        	make -n | tail -n 1 | sed 's/.*'"${myLDFLAGS}"'//' > "${originalLDFlagsCache}"
    	fi
    	originalLDFLAGS=$(cat "${originalLDFlagsCache}")
   		make -j$(getconf _NPROCESSORS_ONLN)
    fi

    local libDir=${buildDir}/lib
    local binDir=${buildDir}/bin
    local register=${libDir}/libpass.register.so
    local block=${libDir}/libpass.coverage.block.so
    local branch=${libDir}/libpass.coverage.branch.so
    local passes="${block} ${branch}"
    local loadPasses="-load=${block} -load=${branch}"
    local runtimes=${libDir}/libruntime.coverage.bc
    local src=${target}.0.5.precodegen.bc
    local dependencies="${src} ${passes}"
    local bc=${target}.0.6.coverage.bc
    local all=${target}.coverage.bc
    local obj=${target}.coverage.o
    local exe=${target}.coverage
    local libraries="-lstdc++ -lstdc++fs -pthread -ldl -L${CLANG_HOME}/lib -lLLVMSupport"
    local opt=${binDir}/opt-9
    local link=llvm-link
    local optLevel=-O3
    local optArgs="${loadPasses} ${src}"
    local linkArgs="${flto} ${obj} ${libraries} ${originalLDFLAGS}"

	ninja -C ${buildDir} main

    # optimize (instrument), compile bc to obj, and then link everything
    # TODO this shouldn't have to be -O3

    # I put these commands in a Makefile instead to cache things.
#    ${opt} ${optArgs} -o ${bc}
#    ${cc} ${bc} ${runtimes} -c -o ${obj}
#    ${cc} ${linkArgs} -o ${exe}

	bc=${bc} all=${all} obj=${obj} exe=${exe} \
	cc=${cc} opt=${opt} link=${link} \
	dependencies=${dependencies} \
	optLevel=${optLevel} optArgs=${optArgs} \
	runtimes=${runtimes} linkArgs=${linkArgs} \
	make -f ${srcDir}/FuzzMakefile

	local sourceMapExt=blocks.map
	local tempBlocksSourceMap=ld-temp.o.${sourceMapExt}
	if [[ -f "${tempBlocksSourceMap}" ]]; then
    	mv ${tempBlocksSourceMap} ${target}.${sourceMapExt}
	fi

}

fuzz "$@"
